name: Build and Deploy WebGL

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Unity
      uses: game-ci/unity-actions/setup@v2
      with:
        unityVersion: 2022.3.22f1
    - name: Build project
      run: |
        mkdir build
        Unity -projectPath . -buildTarget WebGL -quit -batchmode -nographics -buildPath build/WebGL
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build/WebGL
