name: Build and Deploy Unity WebGL

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Unity
        uses: game-ci/unity-actions@v2
        with:
          unityVersion: '2022.3.22f1'

      - name: Build Unity WebGL
        run: |
          mkdir -p Build/WebGLBuild
          unity -batchmode -nographics -quit -projectPath . -buildWebGLPlayer Build/WebGLBuild

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: Build/WebGLBuild
          token: ${{ secrets.GITHUB_TOKEN }}
